name: start-services

on:
  workflow_call:
    inputs:
      environment:
        description: environment variables
        type: string
        required: true

jobs:
  start-service:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: start
        run: echo "${{ vars.NAME }}"
