name: stop-services

on:
  workflow_call:
    inputs:
      environment:
        description: environment variables
        type: string
        required: true

jobs:
  stop-service:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: stop
        run: echo "service stopped"
