name: Orchestration
on:
  workflow_dispatch:
    inputs:
      environment: 
        description: choose the envrionemt
        type: choice
        required: true
        options:
          - tst
          - acc
          - prd
    

jobs:
  start-service:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: show vars
        run: echo "${{ vars.NAME }}"

  Apply-Patching:
    needs: start-service
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Greeter
        run: echo "Hi Welcome"

      