name: Orchestration
on:
  workflow_dispatch:
    inputs:
      environment: 
        - tst
        - acc
        - prd
        # description: choose the envrionemt
        # type: string
        # required: true
  

jobs:
  start-service:
    runs-on: ubuntu-latest
    steps:
      - name: show vars
        run: echo "Hellpw world"