name: Patching

on:
  workflow_call:
    inputs:
      environment:
        description: environment variables
        type: string
        required: true

jobs:
  apply-patching:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: stop
        run: echo "${{ vars.NAME }}"
