


name: Terraform

on:
  push:
    branches:
      - main 

env:
  ROOT_PATH = '${{ github.workspace }}/src'

jobs:
  terraform-plan:
    name: Terraform
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: init
        run: terraform init 
        working-directory: ${{env.ROOT_PATH}}


      - name: plan
        run: terraform plan
        working-directory: ${{env.ROOT_PATH}}



        


